openapi: 3.0.0
x-stoplight:
  id: ydjgcb24txqx1
info:
  title: Qstn Api Spec
  version: '1.0'
  description: Question project api docs
  contact:
    name: Boltcliq
    email: dev@boltcliq.com
    url: 'https://boltcliq.com'
servers:
  - url: 'http://localhost:7000'
paths:
  /v1/auth/signup:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  x-stoplight:
                    id: 4exxq50nwvbwo
              required:
                - email
                - password
            examples: {}
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      tags:
        - auth
    parameters: []
  /v1/auth/login:
    post:
      summary: Sign In
      operationId: sign-in
      responses:
        '200':
          description: Login Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Credential Error
        '404':
          description: User not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  x-stoplight:
                    id: 4exxq50nwvbwo
              required:
                - email
                - password
            examples: {}
        description: Use the email and password to login
      description: Login
      parameters: []
      tags:
        - auth
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        email:
          type: string
          format: email
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - email
        - emailVerified
tags:
  - name: auth
